### PR TITLE
add mass assignment setter and initializer

### LINKED ISSUE #208: `cast` method for applying changes from an attribute hash
In my current application, I have a lot of methods that build up new instances of model objects and then do work with them. Currently (at least as far as I'm aware), the only way of doing this with Crecto directly is calling `Model.new` and then applying each parameter individually. I've seen some other libraries that provide auto constructors, though I'm not actually sure if they would work with `Changeset`s properly...

I'd like to see something similar to Ecto's [`cast/4`](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/4) for applying multiple changes to a model at once given an attribute hash. The main, immediate benefits that I see in this method are automatically applying multiple changes at once and "whitelisting" attributes that can be changed.

As a temporary solution, I've implemented this code as part of `Schema` (the only place I was able to access the `CRECTO_FIELDS` constant) and it seems to be working fairly well:

```crystal
def cast(attrs)
  attrs.each do |field, value|
    case field.to_s
      {% for model_field in CRECTO_FIELDS %}
      when "{{model_field[:name].id}}"
        self.{{model_field[:name].id}} = value.as({{model_field[:type].id}})
      {% end %}
    end
  end
  self.class.changeset(self)
end
```

This method returns a `Changeset` so that you can immediately check for errors easily. An example usage looks like this:

```crystal
class User < Crecto::Model
  schema "users" do
    field :name, String
    field :job_title, String
    field :age, Int32
  end

  validate_required :age
end

def create_user(**attrs)
  user = User.new.cast(attrs)
end

user = create_user(name: "Jon", job_title: "developer", irrelevant_field: 2351)

puts user.instance.to_json #=> {"name":"Jon","job_title":"developer"}
puts user.errors #=> [{:field => "age", :message => "is required"}]
```

Additionally, since `Repo.insert` and the like accept changesets as arguments, this naturally leads into a cast->insert pattern:

```crystal
user = create_user(name: "Jon", job_title: "developer", irrelevant_field: 2351)
if user.valid?
  Repo.insert(user)
end
```

**tl;dr** I'd like to port over Ecto's [`cast/4`](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/4) to make it easier to create and work with model instances. I've got a temporary solution in place for myself, but a full solution would need to better support things like associations and accepting changesets as arguments.

### PR DESCRIPTION
**Pull request by jreinert**
fixes #208

### CODE REVIEW

**Comment by jreinert** [comment]
This will provide compile-time checked mass assignment methods. The method name `#attributes=` is from Rails ORMs and up for discussion.

**Comment by faultyserver** [comment]
I'm more inclined to stick with the `cast` style in accordance with Ecto rather than moving back to the ActiveRecord style `attributes=`.

Another big advantage of `cast` is that it gracefully handles attributes that are not part of the object being casted. For example, in the issue I posted I had this sample usage:

```crystal
def create_user(**attrs)
  user = User.new.cast(attrs)
end

user = create_user(name: "Jon", job_title: "developer", irrelevant_field: 2351)
```

where `irrelevant_field` is _not_ a property of the `User` model being casted (this also used kwargs instead of a params hash, but that isn't super relevant), but the cast succeeds because it is simply ignored. This pattern essentially acts like using Rails' `strong_params` but directly on the model, avoiding the need for every controller to sanitize user input before casting.

Ideally, `cast` would also let you whitelist attributes to assign from the parameters at call time rather than blankly accepting all of them all the time. This goes hand-in-hand with having `cast` work with Changesets as well, where you could define multiple changeset methods for different operations (e.g., a `creation_changeset` for creating a new User with a username and password, and `update_changeset` that doesn't accept username changes). [This article](http://cultofmetatron.io/2017/04/22/thinking-in-ecto---schemas-and-changesets/) has a nice explanation of the advantages of this model and some examples of using it.

**Comment by jreinert** [comment]
Hey, sorry I was on vacation. How about a `#cast(attributes)` and a `cast!(attributes)` method? The latter would behave like the current `#attributes=` method. The former could just ignore unknown fields. Both could also accept an optional whitelist tuple, which would limit the assignments to the fields defined in it.

**Comment by fridgerator** [comment]
@jreinert I like that

**Comment by jreinert** [comment]
Alright. It was quite a pain to implement but here they are. Runtime checked mass assignment methods.

**Comment by jreinert** [comment]
I don't like the obvious duplication of the cast methods for Hash(Symbol, ...) and Hash(String, ...) but i found no obvious way to DRY it up.

**Comment by shiba-hiro** [comment]
@jreinert 

> I don't like the obvious duplication of the cast methods for Hash(Symbol, ...) and Hash(String, ...)

How about something like this?
Although it may be a bit complicated to write just 2 methods...

```crystal
KEY_TYPES = [String, Symbol]

{% for key_type in KEY_TYPES %}
  def sample(args : Hash({{key_type}}, Int32))
    p args
  end
{% end %}

sample Hash{"string" => 1}
# {"string" => 1}

sample Hash{:hash => 2}
# {:hash => 2}
```

**Comment by faultyserver** [comment]
I’m not sure support for a hash with symbol keys needs to be added. Generally in my experience you either end up with a Hash with string keys (e.g., coming from http params) or a NamedTuple (e.g., from a double splat). A hash with symbol keys doesn’t seem to come up too often, at least for me.

**Comment by jreinert** [comment]
@shiba-hiro unfortunately it's not that simple. For string keys I have to stringify the field names from `CRECTO_FIELDS` before checking for existence / assigning.

I'm actually more inclined to @faultyserver's point of view. Creating symbols from runtime data isn't a good idea (vuln for memory leak attacks).

**Comment by shiba-hiro** [comment]
@jreinert 
> unfortunately it's not that simple. 

oh, I see,,, Thank you for your comment.

**Comment by jreinert** [comment]
@fridgerator any comments? :)

**Comment by jreinert** [comment]
> `cast!` will try and apply all parameters to the model, and `cast` will only apply attributes known by the model?
Yes, also cast will accept an additional optional whitelist param which will limit assignments to attributes defined in the whitelist. The benefit of `cast!` is basically just better type safety. It can be checked at compile time. Great for usage with prism params for example which are named tuples.

**Comment by fridgerator** [comment]
Also I noticed he sqlite specs passed for this PR 😡

**Pull request merged**
