### PR TITLE
Get by query

### PR DESCRIPTION
**Pull request by jreinert**
Adds overloads for using get_by and get_by! with query objects

### CODE REVIEW

**Comment by fridgerator** [comment]
Nice!  That stupid sqlite test fails sometimes with that error at random places on Travis CI, and I cannot replicate it locally.  I've literally resorted to adding `sleep` to get it to pass :(    https://github.com/Crecto/crecto/blob/9f74ae16a1e1b526e9eb44f032686cdfb4153146/spec/transactions_spec.cr#L35

**Comment by jreinert** [comment]
is there something i can do?

**Comment by fridgerator** [comment]
Well i'm not really sure what the issue is.  Do you use Linux?  I can't replicate it on Mac :(

**Comment by jreinert** [comment]
Yeah i use linux

**Pull request merged**
