### PR TITLE
fix: close query after deletion

### LINKED ISSUE #114: #delete connection leak

### PR DESCRIPTION
**Pull request by vladfaust**
Fixes #114

### CODE REVIEW

**Comment by fridgerator** [comment]
@vladfaust I suspect `delete_all` also has a connection leak, trying to figure out why.  Also not sure why closing the result set causes spec errors.

**Comment by fridgerator** [comment]
Didn't mean to close

**Comment by fridgerator** [comment]
This is also hard to test.  If you comment line 175 in base_adapter.cr `q.push "RETURNING *" if conn.is_a?(DB::Database)`, does this also solve the connection leak for you?

**Comment by fridgerator** [comment]
Nope, that doesn't seem to solve the issue.  I'm starting to think this is a crystal-db or crystal-pg issue

**Comment by vladfaust** [comment]
I don't know

**Comment by vladfaust** [comment]
Can't you edit my commit? You may merge fixing #114 and then pull request a fix for `#delete_all`

**Comment by fridgerator** [comment]
I don't want to merge with breaking tests.  For some reason your commit fixes the leak, but causes several other tests to fail.  We just need to figure out why they are failing.

**Pull request closed without merging**
