### PR TITLE
(#90) Initial work on Enum support.

### PR DESCRIPTION
**Pull request by faultyserver**
THIS PR IS NOT FEATURE COMPLETE.

### TODO

  - [X] Add `enum_field` macro to schema definitions
  - [X] Define backing column field for enum values
  - [X] Support user-defined `column_name` option
  - [x] Support user-defined `column_type` option (`String | Int32`) (half implemented)~
  - [ ] Allow querying by enum value
  - ~Support nilable enum values~

  `schema` now allows users to define an `enum_field`, which takes a field name and an enum type to create a "virtual" field on the model (not the same as using `field, virtual: true`). `enum_field` will additionally create a backing String field to send to/read from the database (ENUMs in databases are largely unsupported and considered bad practice).

Users can then interact with the field directly via the `enum_field` declaration, ensuring type-safety and value restriction at compile-time:

```crystal
class Vehicle < Crecto::Model
  enum Make
    SEDAN
    TRUCK
  end

  schema "vehicles" do
    enum_field :make, Make
  end
end

v = Vehicle.new
v.make = Vehicle::Make::SEDAN

v = Repo.all(Vehicle).first
v.make # => SEDAN

sedans = Repo.all(Vehicle, Query.where(make_string: "SEDAN")
# Ideally, this will also work directly on the enum field.
sedans = Repo.all(Vehicle, Query.where(make: Vehicle::Make::SEDAN)
```

See #90 for rationale and more details.

### CODE REVIEW

**Comment by fridgerator** [comment]
Nice work!

**Comment by faultyserver** [comment]
> Support nilable enum values

I'm having a lot of trouble figuring out how to do this effectively. The following doesn't work nicely:

```crystal
schema "vehicles" do
  enum_field :state, State?
end
```

because `State?` is [parsed as `::Union(State, ::Nil)`](https://github.com/crystal-lang/crystal/pull/2742), and it breaks any usage of the type (`State`) as the receiver for methods. For example:

```crystal
# in the `setup` macro:
{{field_type}}.parse(@{{column_name.id}} || "")

# expands to
::Union(State, ::Nil).parse(@state_string || "")
```

which leads to a compiler error that `Nil` has no method `parse`.

I'm okay with just dropping that feature unless its something people think is important.

**Comment by faultyserver** [comment]
I'm puzzled by this failure: https://travis-ci.org/Crecto/crecto/jobs/236572003#L480

I can't reproduce it locally :/ Can anyone else run the spec with sqlite3 and see if this comes up?

**Comment by fridgerator** [comment]
I'm ok with leaving out nilable enums for now, does this mean the user will have to set it on instance initialization?

I can check the sqlite3 error in a little while.

**Comment by faultyserver** [comment]
> does this mean the user will have to set it on instance initialization?

Yes. I think that's an okay requirement, because I see the primary use case of `enum_field`s being state machines and the like where a null value doesn't particularly make sense. An easy solution in most cases would be to set the value of the enum field in the initializer for the model.

Another option would be to accept a `default` parameter to make things a little cleaner for users. Usage would then be something like this:

```crystal
schema "vehicles" do
  enum_field :state, default: State::OFF
end

v = Repo.insert(Vehicle.new).instance
v.state # => OFF
```

I think that would also apply well for regular `field`s, though, so maybe it's better done in another PR?

> I can check the sqlite3 error in a little while.

Thanks :)

**Comment by faultyserver** [comment]
Turns out I was testing on MySQL instead of SQLite3 and now I am reproducing that error -.-

A little debugging led to a `cast from Int64 to Int32 failed` coming from [this line](https://github.com/Crecto/crecto/pull/92/files#diff-75f1e7a36d9989e79d1ebf46ad50b500R195):

```crystal
@{{field_name}} ||= {{field_type}}.new(@{{column_name}}.as?({{column_type}}) || 0)
```

(Note: this line doesn't actually raise the error. Removing the `?` does. With the question mark, the value defaults to 0, or the first entry of the enum type. In this case, that was `COUPE` instead of `SEDAN`).

Changing the line to look like this makes the test pass:

```crystal
@{{field_name}} ||= {{field_type}}.new(@{{column_name}}.not_nil!.to_i32)
```

Which is probable the better solution anyway, but definitely makes supporting nilable fields more difficult.

**Comment by fridgerator** [comment]
> I think that would also apply well for regular fields, though, so maybe it's better done in another PR?

Defaults is in the roadmap, the only way I could think to do it was to set the defaults in crecto model's initialize methods.  One problem with this though is that if the user overrides it for whatever reason, the defaults wont work.

**Comment by fridgerator** [comment]
This branch looks good to me.

Thanks for contributing, much appreciated.

**Pull request merged**
