### PR TITLE
Only includes association implementations when necessary

### PR DESCRIPTION
**Pull request by jianghengle**
I am working on a Crecto Admin app with 126 tables in a MySQL database using Crecto. When I compiled the app, it took over 30 minutes and generated a binary of ~250MB. Accidentally, I removed the association methods and recompiled the app, and surprisedly it only took 28 seconds and generated a binary of 34MB, which is much shorter and smaller.

So I made this PR, which does not change any logic, but only refactored to includes the association implementations in the models which have associations. I was trying to only exclude the methods totally and use `responds_to?` to determine if the model has those methods, but I run into a compiler crash bug which I could not figure out why. So I keep the empty implementation ins the model, and the real implementations are in the `macro setup_associations` to be called in the `has_one`, `has_many` and `belongs_to` macroes. And when those methods are called in the `repo.cr` and `base_adapter.cr`, just check if the return is `nil` to continue or return directly.

### CODE REVIEW

**Comment by jreinert** [comment]
Wow! Awesome work! And great to know there are people using Crecto for serious applications!

**Comment by fridgerator** [comment]
Nice!

**Comment by jianghengle** [comment]
Ok, will combine the commits by rebase or something else. But probably tomorrow since I am now on the flight back to Beijing.

**Comment by jianghengle** [comment]
OK, I combined the commits into one, but still needed another one to solve the conflict with the master. Please review the PR.

**Pull request merged**
